package MooseX::StrictAttributes::Meta::Class::Trait::StrictAttributeIsas;
use Moose::Role;

with 'MooseX::StrictAttributes::AddDefaultAttributeTrait';

__PACKAGE__->__generate_attribute_trait_appender('StrictIsa');

1;

__END__


=head1 NAME

MooseX::StrictAttributes::Meta::Class::Trait::StrictAttributeIsas - A class metaclass role which
composes an ISA strictness trait into all attributes generated by the metaclass.

=head1 SYNOPSIS

    package My::Class
    use Moose -traits => [qw/ StrictAttributeIsas /];
    
    has foo ( isa => 'Bar' );
    
=head1 DESCRIPTION

Composes the trait L<MooseX::StrictAttributes::Meta::Attribute::Trait::Isa> into all attributes.

=head1 BUGS AND SOURCE CODE

This software probably contains bugs somewhere, and the way in which some components
are implemented is not optimal.

Patches welcome. Please ask in #moose for commit bits.

The source code for this project is in the Moose repository at L<http://code2.0beta.co.uk/moose/svn/>

=head1 AUTHORS

Tomas Doran <bobtfish@bobtfish.net> (t0m on #moose)

=head1 COPYRIGHT AND LICENSE

Copyright 2008 Tomas Doran.

This library is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

